<?php

namespace api\modules\v1\models;

use api\helpers\UserHelp;
use \yii\db\ActiveRecord;
use yii\helpers\Url;

/**
 * Country Model
 *
 * @author Budi Irawan <deerawan@gmail.com>
 */
class Trip extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ts_trip';
    }

    /**
     * @inheritdoc
     */
    public static function primaryKey()
    {
        return ['id'];
    }

    /**
     * Define rules for validation
     */
    public function rules()
    {
        return [
            [['name', 'destination', 'pretty_url', 'img_url'], 'string', 'max' => 255],
            ['description', 'string', 'max' => 1024],
            [['url', 'original_img_url'], 'url'],
            [['user_id', 'pic_id', 'created', 'updated', 'cloned', 'yr', 'mth', 'day', 'is_private', 'is_featured'], 'integer'],
            ['state', 'in', 'range' => ['pending', 'active', 'disabled']]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->state = 'pending';
        $this->updated = $this->created = time();

    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getDestinations()
    {
        return $this->hasMany(TripDestination::className(), ['trip_id' => 'id']);
    }

    public function getAccess()
    {
        return $this->hasMany(TripAccess::className(), ['trip_id' => 'id']);
    }

    public function getFav()
    {
        return $this->hasMany(TripFav::className(), ['trip_id' => 'id']);
    }

    public function getSpots()
    {
        return $this->hasMany(Spot::className(), ['trip_id' => 'id']);
    }
    
    public function getPublicUrl(){
        $url = Url::to('@webapp'. '#!/trip/public/'.$this->id,true);
        return $url;
    }


}
